[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
bsc = "${BSC_RPC_URL}"

[bscscan]
bsc = { key = "${BSCSCAN_API_KEY}" }
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
